---
- block:
  - name: "uploading nomad server certificates " 
    copy: 
      src: "{{ certificate_root_dir }}/nomad/{{ inventory_hostname }}/{{ item }}.enc"
      dest: "{{ nomad_tls_path }}/{{ item }}"
      force: yes
      decrypt: yes
      owner: nomad
    loop: ['ca.pem','server.pem','server-key.pem'] 
  - name: "uploading nomad retry-join client certificate" 
    copy: 
      src: "{{ certificate_root_dir }}/nomad/{{ nested_loop.0 }}/{{ nested_loop.1 }}.enc"
      dest: "{{ nomad_config_directory_path }}/certificates/{{ nested_loop.0 }}/{{ nested_loop.1 }}"
      force: yes
      decrypt: yes
    with_nested:
      - "{{ retry_join_ips }}"
      - ["ca.pem" , "client.pem", "client-key.pem"]
    loop_control:
      loop_var: nested_loop

  become: yes
  when :
    - not nomad_tls_disable
